# Generated by Django 4.1.3 on 2022-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(default='Some Address', max_length=50),
            preserve_default=False,
        ),
    ]
