# Generated by Django 4.1.3 on 2022-11-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pk',)},
        ),
    ]
